# Generated by Django 4.2.1 on 2023-07-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('number', 'device')},
        ),
    ]
