# Generated by Django 4.2.1 on 2023-07-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_port_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='port',
            unique_together=set(),
        ),
    ]
